import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AgGridProviderWrapper } from "../providers/AgGridProviderWrapper";
import { LogoutButton } from "@/shared/ui/LogoutButton";
import { createClient } from "@/utils/supabase/server";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const supabase = await createClient();
	const {
		data: { user },
	} = await supabase.auth.getUser();
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased text-white bg-black`}>
				<AgGridProviderWrapper>
					{user && (
						<header className="fixed top-0 left-0 right-0 h-16 bg-neutral-900 border-b border-white/10 flex items-center justify-between px-8 z-50">
							<div className="font-bold text-xl tracking-tight">Project</div>
							<LogoutButton />
						</header>
					)}
					<main className={user ? "pt-16" : ""}>{children}</main>
				</AgGridProviderWrapper>
			</body>
		</html>
	);
}
